export const HEARTFILLED = "HEARTFILLED";
export const HEARTOUTLINED = "HEARTOUTLINED";
export const DOBUTTONICON = "DOBUTTONICON";
export const BUTTONICON = "BUTTONICON";
export const SELECTCOLOR = "SELECTCOLOR";
export const UNSELECTCOLOR = "UNSELECTCOLOR";
export const SELECTSIZE = "SELECTSIZE";
export const UNSELESIZE = "UNSELESIZE";